@ProductManagementCatalogue.API_HostAddress = http://localhost:5069

GET {{ProductManagementCatalogue.API_HostAddress}}/products/1
Content-Type: application/json

###
POST {{ProductManagementCatalogue.API_HostAddress}}/products
Content-Type: application/json
Accept: application/json
{
  "name": "Sample Product",
  "description": "A sample product for testing.",
  "price": 19.99,
  "stock": 100,
  "isActive": true
}

###
PATCH {{ProductManagementCatalogue.API_HostAddress}}/products/2
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Product Name",
  "description": "Updated product description.",
  "price": 29.99,
  "stock": 50,
  "isActive": false
}